/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var EmergencyPowerActivated:String = "event:/Music/EmergencyPowerActivated";
    public static inline var OutsideTheMines:String = "event:/Music/OutsideTheMines";
}

class FmodSFX {
    public static inline var Siren:String = "event:/SFX/Cutscene/Siren";
    public static inline var Type:String = "event:/SFX/Hud/Type";
    public static inline var Typewriter:String = "event:/SFX/Hud/Typewriter";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
}
